-- NYC Taxi Data Warehouse star schema.
-- Physical table names are lowercase to avoid quoted identifier issues in PostgreSQL.

DROP TABLE IF EXISTS fact_trip CASCADE;
DROP TABLE IF EXISTS dim_time CASCADE;
DROP TABLE IF EXISTS dim_pickup_location CASCADE;
DROP TABLE IF EXISTS dim_dropoff_location CASCADE;
DROP TABLE IF EXISTS dim_payment CASCADE;
DROP TABLE IF EXISTS dim_service CASCADE;

CREATE TABLE dim_time (
    time_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pickup_date DATE NOT NULL,
    year SMALLINT NOT NULL CHECK (year BETWEEN 2000 AND 2100),
    quarter SMALLINT NOT NULL CHECK (quarter BETWEEN 1 AND 4),
    month SMALLINT NOT NULL CHECK (month BETWEEN 1 AND 12),
    day SMALLINT NOT NULL CHECK (day BETWEEN 1 AND 31),
    hour SMALLINT NOT NULL CHECK (hour BETWEEN 0 AND 23),
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    is_weekend BOOLEAN NOT NULL,
    UNIQUE (pickup_date, hour)
);

CREATE TABLE dim_pickup_location (
    location_id INTEGER PRIMARY KEY CHECK (location_id > 0),
    zone VARCHAR(120) NOT NULL,
    borough VARCHAR(80) NOT NULL,
    city VARCHAR(80) NOT NULL DEFAULT 'New York City'
);

CREATE TABLE dim_dropoff_location (
    location_id INTEGER PRIMARY KEY CHECK (location_id > 0),
    zone VARCHAR(120) NOT NULL,
    borough VARCHAR(80) NOT NULL,
    city VARCHAR(80) NOT NULL DEFAULT 'New York City'
);

CREATE TABLE dim_payment (
    payment_id SMALLINT PRIMARY KEY,
    payment_type VARCHAR(40) NOT NULL,
    payment_category VARCHAR(40) NOT NULL
);

CREATE TABLE dim_service (
    service_id SMALLINT PRIMARY KEY,
    vendor_id SMALLINT NOT NULL UNIQUE,
    vendor_name VARCHAR(80) NOT NULL,
    service_type VARCHAR(40) NOT NULL
);

CREATE TABLE fact_trip (
    trip_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time_id BIGINT NOT NULL REFERENCES dim_time(time_id),
    pickup_location_id INTEGER NOT NULL REFERENCES dim_pickup_location(location_id),
    dropoff_location_id INTEGER NOT NULL REFERENCES dim_dropoff_location(location_id),
    payment_id SMALLINT NOT NULL REFERENCES dim_payment(payment_id),
    service_id SMALLINT NOT NULL REFERENCES dim_service(service_id),
    fare_amount NUMERIC(10, 2) NOT NULL CHECK (fare_amount > 0),
    tip_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(10, 2) NOT NULL CHECK (total_amount > 0),
    trip_distance NUMERIC(10, 2) NOT NULL CHECK (trip_distance > 0),
    passenger_count SMALLINT NOT NULL CHECK (passenger_count BETWEEN 1 AND 6),
    trip_duration NUMERIC(8, 2) NOT NULL CHECK (trip_duration BETWEEN 1 AND 300)
);

CREATE INDEX idx_fact_trip_time_id ON fact_trip(time_id);
CREATE INDEX idx_fact_trip_pickup_location_id ON fact_trip(pickup_location_id);
CREATE INDEX idx_fact_trip_dropoff_location_id ON fact_trip(dropoff_location_id);
CREATE INDEX idx_fact_trip_payment_id ON fact_trip(payment_id);
CREATE INDEX idx_fact_trip_service_id ON fact_trip(service_id);

COMMENT ON COLUMN dim_time.day_of_week IS 'ISO day of week: 1=Monday, 7=Sunday.';
COMMENT ON CONSTRAINT dim_time_pickup_date_hour_key ON dim_time IS 'DimTime uses one row per pickup date and hour.';
